Update update-stats.yml

diff --git a/.github/workflows/update-stats.yml b/.github/workflows/update-stats.yml
--- a/.github/workflows/update-stats.yml
+++ b/.github/workflows/update-stats.yml
@@ -33,6 +33,14 @@ jobs:
           git checkout -b update-stats-branch
           git add .
           git commit -m "chore: update stats (auto)" || echo "No changes"
+      - name: Debug secret
+        run: |
+          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
+            echo "PAT_TOKEN is missing!"
+            exit 1
+          else
+            echo "PAT_TOKEN is set (hidden)."
+          fi
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v7
